packages:
  - notoko-web-ui
  - packages/@notoko/*

catalog:
  '@alenaksu/json-viewer': ^2.1.2
  '@jsfe/shoelace': ^0.4.0
  '@pinyin-pro/data': 1.2.0
  '@shoelace-style/shoelace': ^2.20.1
  '@solid-primitives/media': ^2.3.3
  '@solidjs/meta': ^0.29.4
  '@solidjs/router': ^0.15.0
  '@solidjs/start': ^1.1.0
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.0.7
  '@types/micromatch': ^4.0.10
  '@types/node': 24.10.1
  alien-signals: 3.1.1
  daisyui: ^5.5.5
  es-toolkit: 1.42.0
  jsonc-parser: ^3.3.1
  micromatch: ^4.0.8
  pinyin-pro: 3.27.0
  rolldown: 1.0.0-beta.53
  rollup-plugin-copy: ^3.5.0
  rollup-plugin-license: ^3.6.0
  solid-icons: ^1.1.0
  solid-js: 1.9.10
  solid-sonner: ^0.2.8
  tailwindcss: ^4.0.7
  ts-pattern: 5.9.0
  vinxi: ^0.5.7
  vitest: 4.0.14
  zod: 4.1.13
