packages:
  - notoko-web-ui
  - lib-js/@notoko/*

catalog:
  '@jsonforms/material-renderers': ^3.7.0
  '@jsonforms/react': ^3.7.0
  '@mui/material': ^7.3.5
  '@r2wc/react-to-web-component': ^2.1.0
  '@rjsf/core': ^6.1.2
  '@rjsf/mui': ^6.1.2
  '@rjsf/utils': ^6.1.2
  '@rjsf/validator-ajv8': ^6.1.2
