import * as _ from "es-toolkit";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { type IChangeEvent, withTheme } from "@rjsf/core";
import { Theme } from "@rjsf/mui";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import validator from "@rjsf/validator-ajv8";

const lightTheme = createTheme({ palette: { mode: "light" } });
const darkTheme = createTheme({ palette: { mode: "dark" } });

/**
 * Although the web UI uses daisyUI, and rjsf also supports to be themed with
 * daisyUI, we intentionally choose MUI here instead, so that users can tell
 * which part of the UI is generated by rjsf.
 */
const Form = withTheme(Theme);

export function Wrapper(props: {
  dark: boolean;
  schema: any;
  data: any;
}) {
  const divRef = useRef<HTMLDivElement>(null);

  const [data, setData] = useState(props.data);
  const isUnsaved = //
    useMemo(() => !_.isEqual(data, props.data), [data, props.data]);
  const [isOutOfSync, setIsOutOfSync] = useState(false);

  useEffect(() => {
    if (isOutOfSync) return;
    if (isUnsaved) {
      setIsOutOfSync(true);
      return;
    }
    setData(props.data);
  }, [props.data]);
  useEffect(() => {
    const ev = new Event("rjsf:setIsUnsaved", { bubbles: true });
    (ev as any).data = isUnsaved;
    divRef.current?.dispatchEvent(ev);
  }, [isUnsaved]);
  useEffect(() => {
    if (isOutOfSync) {
      const ev = new Event("rjsf:outOfSync", { bubbles: true });
      divRef.current?.dispatchEvent(ev);
    }
  }, [isOutOfSync]);

  const handleChange = useCallback((data: IChangeEvent) => {
    setData(data.formData);
  }, []);
  const handleSubmit = useCallback((data: IChangeEvent) => {
    const ev = new Event("rjsf:submit", { bubbles: true });
    (ev as any).data = data.formData;
    divRef.current?.dispatchEvent(ev);
    setIsOutOfSync(false);
  }, []);

  return (
    <div style={{ display: "contents" }} ref={divRef}>
      <ThemeProvider theme={props.dark ? darkTheme : lightTheme}>
        <Form
          schema={props.schema}
          formData={data}
          onChange={handleChange}
          onSubmit={handleSubmit}
          validator={validator}
        />
      </ThemeProvider>
    </div>
  );
}
